citadel_version: 4
metadata:
  name: ThunderHub
  version: 0.13.23
  category: Lightning Node Management
  tagline: Take full control of your Lightning node
  developers:
    Anthony Potdevin: https://apotdevin.com
  description: |-
    ThunderHub allows you to take full control of your Lightning node with a slick and awesome UI. Explore all the options that ThunderHub has to offer, from sending and receiving Lightning payments, to checking your node's health statistics, and even more advanced options like channel rebalancing and multi-path lightning payments.

    Managing and monitoring your node has never been easier with transaction reports, graphs and a huge assortment of different features all bundled inside of this great tool.
  permissions:
  - lnd
  repo:
    Public: https://github.com/apotdevin/thunderhub
  support: https://t.me/thunderhub
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: $APP_SEED
services:
  main:
    image: apotdevin/thunderhub:v0.13.23@sha256:e285abb2f997a75e69968b2e4279350b3ef0a495dc6e93fe37f12fb73c9f43b2
    environment:
      LOG_LEVEL: debug
      MASTER_PASSWORD_OVERRIDE: $APP_SEED
      NO_VERSION_CHECK: 'true'
      YML_ENV_1: $APP_LND_SERVICE_IP:10009
      ACCOUNT_CONFIG_PATH: /data/thubConfig.yaml
      TOR_PROXY_SERVER: socks://$TOR_PROXY_IP:$TOR_PROXY_PORT
    port: 3000
    mounts:
      data:
        data: /data
      lnd: /lnd
