citadel_version: 4
metadata:
  name: ThunderHub
  version: 0.13.27
  category: Lightning Node Management
  tagline: Take full control of your Lightning node
  developers:
    Anthony Potdevin: https://apotdevin.com
  description: |-
    ThunderHub allows you to take full control of your Lightning node with a slick and awesome UI. Explore all the options that ThunderHub has to offer, from sending and receiving Lightning payments, to checking your node's health statistics, and even more advanced options like channel rebalancing and multi-path lightning payments.

    Managing and monitoring your node has never been easier with transaction reports, graphs and a huge assortment of different features all bundled inside of this great tool.
  permissions:
  - lnd
  repo:
    Public: https://github.com/apotdevin/thunderhub
  support: https://t.me/thunderhub
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: $APP_SEED
services:
  main:
    image: apotdevin/thunderhub:v0.13.27@sha256:340e0f9d9af220f019ec98d398d33b43ba3acec2051838c3a049e54b37c8351c
    environment:
      YML_ENV_1: $APP_LND_SERVICE_IP:10009
      NO_VERSION_CHECK: 'true'
      ACCOUNT_CONFIG_PATH: /data/thubConfig.yaml
      MASTER_PASSWORD_OVERRIDE: $APP_SEED
      TOR_PROXY_SERVER: socks://$TOR_PROXY_IP:$TOR_PROXY_PORT
      LOG_LEVEL: debug
    port: 3000
    mounts:
      data:
        data: /data
      lnd: /lnd
