version: 3
metadata:
  category: Lightning Node Management
  name: ThunderHub
  version: 0.13.21
  tagline: Take full control of your Lightning node
  description: |-
    ThunderHub allows you to take full control of your Lightning node with a slick and awesome UI. Explore all the options that ThunderHub has to offer, from sending and receiving Lightning payments, to checking your node's health statistics, and even more advanced options like channel rebalancing and multi-path lightning payments.

    Managing and monitoring your node has never been easier with transaction reports, graphs and a huge assortment of different features all bundled inside of this great tool.
  developers:
    Anthony Potdevin: https://apotdevin.com
  dependencies:
  - lnd
  repo: https://github.com/apotdevin/thunderhub
  support: https://t.me/thunderhub
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: $APP_SEED
containers:
- name: web
  image: apotdevin/thunderhub:v0.13.21@sha256:f7b42bd7e48bdb43d3f995957f109463fb306515b2a61a05af9300d69bd3ae92
  data:
  - data:/data
  environment:
    NO_VERSION_CHECK: 'true'
    MASTER_PASSWORD_OVERRIDE: $APP_SEED
    LOG_LEVEL: debug
    TOR_PROXY_SERVER: socks://$TOR_PROXY_IP:$TOR_PROXY_PORT
    ACCOUNT_CONFIG_PATH: /data/thubConfig.yaml
    YML_ENV_1: $LND_IP:$LND_GRPC_PORT
  port: 3000
