citadel_version: 4
metadata:
  name: Tailscale
  version: 1.60.0
  category: Networking
  tagline: A VPN to access your Citadel from anywhere
  developers:
    Tailscale Inc.: https://tailscale.com
  description: Tailscale allows you to easily connect to your Citadel node (and home network) from anywhere.
  permissions:
  - network
  repo:
    Public: https://github.com/tailscale/tailscale
  support: https://github.com/tailscale/tailscale/issues
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: /
  defaultPassword: null
services:
  main:
    image: tailscale/tailscale:v1.60.0@sha256:f7f1668801442f2ebafade9792d60f7aa1ede248c89d9fe840fec9cc392b6a50
    stop_grace_period: 1m
    restart: on-failure
    command: sh -c 'tailscale web --listen 0.0.0.0:5000 & exec tailscaled --tun=userspace-networking'
    network_mode: host
    port: 5000
    port_priority: Required
