citadel_version: 4
metadata:
  name: Tailscale
  version: 1.46.1
  category: Networking
  tagline: A VPN to access your Citadel from anywhere
  developers:
    Tailscale Inc.: https://tailscale.com
  description: Tailscale allows you to easily connect to your Citadel node (and home network) from anywhere.
  permissions:
  - network
  repo:
    Public: https://github.com/tailscale/tailscale
  support: https://github.com/tailscale/tailscale/issues
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: /
  defaultPassword: null
services:
  main:
    image: tailscale/tailscale:v1.46.1@sha256:8abcbcfe179c454ab4c3b583626c4e5b2edcb7c0851fe09ba3313d4ca02aacdc
    stop_grace_period: 1m
    restart: on-failure
    command: sh -c 'tailscale web --listen 0.0.0.0:5000 & exec tailscaled --tun=userspace-networking'
    network_mode: host
    port: 5000
    port_priority: Required
