citadel_version: 4
metadata:
  name: Tailscale
  version: 1.40.0
  category: Networking
  tagline: A VPN to access your Citadel from anywhere
  developers:
    Tailscale Inc.: https://tailscale.com
  description: Tailscale allows you to easily connect to your Citadel node (and home network) from anywhere.
  permissions:
  - network
  repo:
    Public: https://github.com/tailscale/tailscale
  support: https://github.com/tailscale/tailscale/issues
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: /
  defaultPassword: null
services:
  main:
    image: tailscale/tailscale:v1.40.0@sha256:a90a608e3c8ec069628d2f62fbf7bde5e9095f9556d1c8d05ea0489537d7a373
    stop_grace_period: 1m
    restart: on-failure
    command: sh -c 'tailscale web --listen 0.0.0.0:5000 & exec tailscaled --tun=userspace-networking'
    network_mode: host
    port: 5000
    port_priority: Required
