citadel_version: 4
metadata:
  name: Gitea
  version: 1.20.2
  category: Development
  tagline: A painless self-hosted Git service
  developers:
    Gitea: https://gitea.io/en-us/
  description: |-
    Gitea is a painless self-hosted Git service. It is similar to GitHub, Bitbucket, and GitLab. It is a community managed lightweight code hosting solution written in Go. Gitea's minimal requirements allow it to run seamlessly on inexpensive hardware like a Raspberry Pi. Features:
    - Fully self-hosted and private
    - Issue tracker
    - Account/Organization/Repository management
    - Tor support
    - Repository Git hooks/deploy keys
    - Repository issues, pull requests and wiki
    - Add/Remove repository collaborators
    - Gravatar and custom source
    - Admin panel
  permissions: []
  repo:
    Public: https://github.com/go-gitea/gitea
  support: https://discourse.gitea.io
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: null
services:
  db:
    image: mariadb:10.6.4@sha256:4bbee12b1adf299211f844ebbe89563675c46965470dcfa40f5278d63c56d030
    user: 1000:1000
    environment:
      MYSQL_USER: gitea
      MYSQL_ROOT_PASSWORD: gitea
      MYSQL_DATABASE: gitea
      MYSQL_PASSWORD: moneyprintergobrrr
    mounts:
      data:
        data/db: /var/lib/mysql
  main:
    image: gitea/gitea:1.20.2@sha256:6e3b85a36653894d6741d0aefb41dfaac39044e028a42e0a520cc05ebd7bfc3f
    user: 1000:1000
    environment:
      GITEA__server__DOMAIN: ${APP_DOMAIN}
      GITEA__database__PASSWD: moneyprintergobrrr
      GITEA__security__INSTALL_LOCK: 'true'
      GITEA__server__HTTP_PORT: ${APP_GITEA_MAIN_PORT}
      GITEA__server__SSH_PORT: 2222
      GITEA__server__SSH_LISTEN_PORT: 2222
      GITEA__database__NAME: gitea
      GITEA__database__HOST: ${APP_GITEA_DB_IP}:3306
      GITEA__database__DB_TYPE: mysql
      GITEA__database__USER: gitea
      GITEA__server__SSH_DOMAIN: ${APP_DOMAIN}
      GITEA__server__START_SSH_SERVER: 'true'
    required_ports:
      tcp:
        2222: 2222
      http: null
      udp: null
    mounts:
      data:
        data/gitea/config: /etc/gitea
        data/gitea/data: /var/lib/gitea
