citadel_version: 4
metadata:
  name: LNDg
  version: 1.6.1
  category: Lightning Node Management
  tagline: Lite GUI web interface to analyze LND data and manage your node with automation.
  developers:
    cryptosharks131: https://github.com/cryptosharks131
  description: LNDg is your command center for running a profitable and efficient routing node. From quickly viewing your node's health, automated rebalancing, selecting new potential peers and much more.
  permissions:
  - lnd
  repo:
    Public: https://github.com/cryptosharks131/lndg
  support: https://t.me/+-RxoZdi7snk2ZGYx
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: ''
  defaultPassword: $APP_SEED
services:
  main:
    image: ghcr.io/cryptosharks131/lndg:v1.6.1@sha256:837ca98d5f7cfb960edb4037b9798311b49edd2d1945571dbbb7cb6c46ae5d76
    stop_grace_period: 1m
    restart: on-failure
    command:
    - sh
    - -c
    - python initialize.py -net '${BITCOIN_NETWORK}' -server '${APP_LND_SERVICE_IP}:10009' -pw '${APP_SEED}' -d && supervisord && python manage.py runserver 0.0.0.0:3000
    port: 3000
    mounts:
      data:
        data: /lndg/data
      lnd: /root/.lnd
