citadel_version: 4
metadata:
  name: Vaultwarden
  version: 1.30.5
  category: Password Managers
  tagline: Unofficial Bitwarden® compatible server
  developers:
    Daniel García: https://github.com/dani-garcia
  description: |-
    Vaultwarden (formerly known as Bitwarden_RS) is an alternative implementation of the Bitwarden® server API written in Rust, compatible with upstream Bitwarden® clients*. Vaultwarden is perfect for self-hosting all of your passwords in an\ encrypted vault on your Citadel. Vaultwarden is a full implementation of Bitwarden® API that includes:
    - Organizations support
    - Attachments
    - Vault API support
    - Serving the static files for Vault interface
    - Website icons API
    - Authenticator and U2F support
    - YubiKey and Duo support

    Please note that Vaultwarden is not associated with the Bitwarden® project nor 8bit Solutions LLC. When using this app, please report any bugs or suggestions to us directly, regardless of whatever clients you are using (mobile, desktop, browser, etc), and do not use Bitwarden®'s official support channels.
  permissions: []
  repo:
    Public: https://github.com/dani-garcia/vaultwarden
  support: https://vaultwarden.discourse.group/
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: null
  torOnly: true
services:
  main:
    image: vaultwarden/server:1.30.5@sha256:edb8e2bab9cbca22e555638294db9b3657ffbb6e5d149a29d7ccdb243e3c71e0
    user: 1000:1000
    environment:
      ROCKET_PORT: '3000'
    port: 3000
