version: 3
metadata:
  category: Networking
  name: Uptime Kuma
  version: 1.23.13
  tagline: Self-hosted uptime monitoring tool
  description: |
    Uptime Kuma is a self-hosted monitoring tool like Uptime Robot.

    Features:

    - Monitoring uptime for HTTP(s) / TCP / HTTP(s) Keyword / Ping / DNS Record / Push / Steam Game Server.
    - Fancy, Reactive, Fast UI/UX.
    - Notifications via Telegram, Discord, Gotify, Slack, Pushover, Email (SMTP), and 70+ notification services.
    - 20 second intervals.
    - Multi Languages
    - Simple Status Page
    - Ping Chart
    - Certificate Info
  developers:
    Louis Lam: https://uptime.kuma.pet
  dependencies: []
  repo: https://github.com/louislam/uptime-kuma
  support: https://github.com/louislam/uptime-kuma/issues
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
containers:
- name: main
  image: louislam/uptime-kuma:1.23.13@sha256:96510915e6be539b76bcba2e6873591c67aca8a6075ff09f5b4723ae47f333fc
  data:
  - data:/app/data
  port: 3001
  restart: on-failure
  stop_grace_period: 1m
