version: 3
metadata:
  category: Automation
  name: Node-RED
  version: 3.1.1
  tagline: Wire together the Internet of Things
  description: |-
    Node-RED is a visual programming tool for wiring together hardware devices, APIs and online services in new and interesting ways.

    It provides a browser-based editor that makes it easy to wire together flows using the wide range of nodes in the palette that can be deployed to its runtime in a single-click.  A built-in library allows you to save useful functions, templates or flows for re-use.

    The flows created in Node-RED are stored using JSON which can be easily imported and exported for sharing with others. An online flow library allows you to share your best flows with the world.

    Warning: Node-RED on Citadel is able to connect directly to Bitcoin Core, LND and Electrum, due to this you should be careful when installing third-party Node-RED nodes.
  developers:
    OpenJS Foundation: https://nodered.org
  dependencies:
  - bitcoind
  - electrum
  - lnd
  repo: https://github.com/node-red/node-red
  support: https://nodered.org/about/community/slack/
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  torOnly: false
  defaultPassword: moneyprintergobrrr
containers:
- name: web
  image: nodered/node-red:3.1.1@sha256:cf9749f31fdaee0a87a27aebf97ef6c051e1b6e77f021806f876055ae8d0b4c8
  data:
  - data:/data
  environment:
    BITCOIN_NETWORK: $BITCOIN_NETWORK
    ELECTRUM_IP: $APP_ELECTRUM_IP
    BITCOIN_RPC_USER: $BITCOIN_RPC_USER
    BITCOIN_RPC_PORT: $BITCOIN_RPC_PORT
    LND_IP: $APP_LND_SERVICE_IP
    PORT: 3000
    ELECTRUM_PORT: 50001
    BITCOIN_RPC_PASS: $BITCOIN_RPC_PASS
    LND_GRPC_PORT: 10009
    BITCOIN_IP: $BITCOIN_IP
  port: 3000
  stop_grace_period: 1m
