version: 3
metadata:
  category: Files
  name: Nextcloud
  version: 26.0.1
  tagline: Your personal cloud
  description: No description yet.
  developers:
    Nextcloud GmbH: https://nextcloud.com
  dependencies: []
  repo: https://github.com/nextcloud/server
  support: https://help.nextcloud.com/categories
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: /login?user=citadel
  defaultPassword: $APP_SEED
containers:
- name: db
  image: mariadb:10.7.1@sha256:832c6e488f49720f484f87ee9f2cd4487321b373db07ac77037860bcd97d92bb
  command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
  data:
  - data/db:/var/lib/mysql
  environment:
    MARIADB_DATABASE: nextcloud
    MARIADB_USER: nextcloud
    MARIADB_ROOT_PASSWORD: password123
    MARIADB_PASSWORD: password123
  user: 1000:1000
- name: redis
  image: redis:6.2.6-bullseye@sha256:0c0484b1d1ff36faace984fe9d8e0fe58892ecc34a4859b97171045b9cd343e1
  data:
  - data/redis:/data
  user: 1000:1000
- name: web
  image: nextcloud:26.0.1@sha256:a320877e5d87da7c7b605d3a2851c40368b668cc075a5d1cf7507d2768de9dfb
  data:
  - data/nextcloud:/var/www/html
  depends_on:
  - db
  - redis
  environment:
    MYSQL_HOST: ${APP_NEXTCLOUD_DB_IP}
    REDIS_HOST: ${APP_NEXTCLOUD_REDIS_IP}
    MYSQL_DATABASE: nextcloud
    NEXTCLOUD_TRUSTED_DOMAINS: ${APP_DOMAIN}:${APP_NEXTCLOUD_WEB_PORT} ${APP_HIDDEN_SERVICE}
    NEXTCLOUD_ADMIN_USER: citadel
    MYSQL_USER: nextcloud
    NEXTCLOUD_ADMIN_PASSWORD: $APP_SEED
    MYSQL_PASSWORD: password123
  port: 80
- name: cron
  image: nextcloud:24.0.4@sha256:69a52f571dc72f9ebbe222fc810f09d016173ec94f4423ea5e3d628496c1a5d5
  data:
  - data/nextcloud:/var/www/html
  depends_on:
  - db
  - redis
  entrypoint: /cron.sh
