version: 3
metadata:
  category: Social
  name: Sphinx Relay
  version: 2.3.1
  tagline: Chat and pay over the Lightning Network
  description: |-
    Sphinx Relay turns your Lightning node into a personal communication server. Messages are end-to-end encrypted and transmitted over the Bitcoin Lightning Network. Download Sphinx on your phone from https://sphinx.chat and pair it with Sphinx Relay on Citadel.

    Communication between Sphinx Relay nodes takes place entirely on the Lightning Network, so it is decentralized, untraceable, and encrypted. Messages are encrypted using client public keys on the Sphinx app.

    You can join tribes at https://tribes.sphinx.chat. If you join a podcast tribe, you can listen to the podcast in Sphinx and stream donations to the host.
  developers:
    Stakwork: https://sphinx.chat
  dependencies:
  - lnd
  repo: https://github.com/stakwork/sphinx-relay
  support: https://t.me/joinchat/Fb4OcRo4LrRD6NXfsNdeeQ
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: /connect
containers:
- name: web
  image: sphinxlightning/sphinx-relay:v2.3.1@sha256:19dd49476fb7a38a8123a2cbfcfe5dc5c1cb1ad69ac0904e9b24657f2943aba3
  data:
  - data:/relay/.lnd/
  environment:
    LND_PORT: 10009
    TLS_LOCATION: /lnd/tls.cert
    CONNECT_UI: 'true'
    LND_LOG_LOCATION: /lnd/logs/bitcoin/${BITCOIN_NETWORK}/lnd.log
    MACAROON_LOCATION: /lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/admin.macaroon
    LND_IP: $APP_LND_SERVICE_IP
    PUBLIC_URL: $APP_HIDDEN_SERVICE:80
  init: true
  port: 3300
