citadel_version: 4
metadata:
  name: LND
  version: 0.16.1-beta
  category: Run a Lightning node
  tagline: An open-source Lightning backend
  developers:
    Lightning Labs: https://github.com/lightningnetwork/lnd
  permissions:
    - bitcoind
    - network
  repo:
    Public: https://github.com/lightningnetwork/lnd
  support: https://t.me/runcitadel
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  path: ""
  defaultPassword: $APP_SEED
  torOnly: false
  description: >-
    LND offers a complete Lightning node that works even while your Bitcoin node is still syncing.
  implements: lightning
services:
  main:
    # TODO: LND UI
    image: ghcr.io/runcitadel/electrum-ui:main@sha256:d3d8126aecd6ee142f4a34900de2c1f3c8e0493ac30b93f1db3f4c1b33bad6ef
    init: true
    port: 8000
    environment:
      BITCOIN_IP: $BITCOIN_IP
      BITCOIN_RPC_PORT: $BITCOIN_RPC_PORT
      BITCOIN_RPC_USER: $BITCOIN_RPC_USER
      BITCOIN_RPC_PASS: $BITCOIN_RPC_PASS
      # Using a public server right now
      ELECTRUM_IP: 104.248.139.211
      ELECTRUM_PORT: 50001
    restart: on-failure

  tor:
    image: lncm/tor:0.4.7.9@sha256:86c2fe9d9099e6376798979110b8b9a3ee5d8adec27289ac4a5ee892514ffe92
    user: toruser
    restart: on-failure
    mounts:
      data:
        torrc: /etc/tor/torrc
        tor: /var/lib/tor/

  service:
    image: lightninglabs/lnd:v0.16.1-beta@sha256:d2044a48fbe35b2941a5fc19328b1314bbe2cf68b628754ada9990b7e6dc1e3b
    user: 1000:1000
    mounts:
      data:
        walletpassword: /walletpassword
        lnd.conf: /data/.lnd/lnd.conf
      shared_data:
        lnd: /data/.lnd
    environment:
      HOME: /data
    restart: on-failure
    stop_grace_period: 5m30s
    required_ports:
      tcp:
        9735: 9735
        10009: 10009
        8080: 8080
    hidden_services:
      grpc:
        10009: 10009
      rest:
        8080: 8080

  neutrino-switcher:
    image: lncm/neutrino-switcher:1.0.5@sha256:3ddf58c5599ba22db8414f2694bfeeba086455d4a19b4955b26c3ae5e967d42a
    restart: on-failure
    mounts:
      data:
        lnd: /lnd
        statuses: /statuses
    environment:
      JSONRPCURL: http://${BITCOIN_IP}:${BITCOIN_RPC_PORT}
      RPCUSER: $BITCOIN_RPC_USER
      RPCPASS: $BITCOIN_RPC_PASS
      # TODO: Find another way of restarting, we can't give apps full root access to docker
      LND_CONTAINER_NAME: lightning
      SLEEPTIME: 3600

  middleware:
    image: ghcr.io/runcitadel/middleware:main@sha256:fdb8b40a651cb4563c754c3f29d1826d32460100c9846d185e8609f0b357eec6
    depends_on:
    - service
    command: sh -c "./wait-for-manager.sh $MANAGER_IP && ./start.sh"
    restart: on-failure
    mounts:
      data:
        lnd: /lnd
      jwt-public-key: /jwt-public-key
    environment:
      PORT: '3000'
      BITCOIN_HOST: $BITCOIN_IP
      RPC_PORT: $BITCOIN_RPC_PORT
      RPC_USER: $BITCOIN_RPC_USER
      RPC_PASSWORD: $BITCOIN_RPC_PASS
      LND_NETWORK: $BITCOIN_NETWORK
      LND_HOST: ${APP_LND_SERVICE_IP}
      JWT_PUBLIC_KEY_FILE: /jwt-public-key/jwt.pem
      DEVICE_HOSTS: ${DEVICE_HOSTS:-"http://citadel.local"}
      UNSAFE_REMOVE_CORS_CHECK: true

  backup:
    image: runcitadel/ln-backups:main@sha256:bda1b8f6c802c8202274970d594e5d21421a4c7932e2a05cb8b37364e3af5eb3
    mounts:
      data:
        lnd: /lnd
    environment:
      BACKUP_ENCRYPTION_KEY: $APP_SEED_2
      BACKUP_ID: $APP_SEED
      TOR_PROXY_IP: $TOR_PROXY_IP
      TOR_PROXY_PORT: $TOR_PROXY_PORT
