citadel_version: 4
metadata:
  name: Tailscale
  version: 1.44.0
  category: Networking
  tagline: A VPN to access your Citadel from anywhere
  developers:
    Tailscale Inc.: https://tailscale.com
  description: Tailscale allows you to easily connect to your Citadel node (and home network) from anywhere.
  permissions:
  - network
  repo:
    Public: https://github.com/tailscale/tailscale
  support: https://github.com/tailscale/tailscale/issues
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: /
  defaultPassword: null
services:
  main:
    image: tailscale/tailscale:v1.44.0@sha256:a1a18e145f9dd0d67ede7ce88f2049eb5ae0c0706f1cea096147170410c2fb57
    stop_grace_period: 1m
    restart: on-failure
    command: sh -c 'tailscale web --listen 0.0.0.0:5005 & exec tailscaled --tun=userspace-networking'
    network_mode: host
    port: 5005
    port_priority: Required
    direct_tcp: true
