version: 3
metadata:
  category: Social
  name: Synapse Admin
  version: 0.10.2
  tagline: Manage your synapse server
  description: 'This app allows you to manage your synapse server. It currently requires some manual work inside Synapse''s Docker container,  so it''s not usable for most users yet. '
  developers:
    Awesome Technologies: https://awesome-technologies.de/https://awesome-technologies.de/
  dependencies: []
  repo: https://github.com/Awesome-Technologies/synapse-admin
  support: https://github.com/Awesome-Technologies/synapse-admin
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
containers:
- name: main
  image: awesometechnologies/synapse-admin:0.10.2@sha256:5636a46f17888ec153380308fdfb7aca09de9153ecf435a5384b769c8e2f6ac0
  port: 80
