citadel_version: 4
metadata:
  name: code-server
  version: 4.90.3
  category: Development
  tagline: Run VS Code on your Citadel
  developers:
    Coder: https://coder.com
  description: This app doesn't  have a description yet.
  permissions: []
  repo:
    Public: https://github.com/cdr/code-server
  support: https://github.com/cdr/code-server/discussions
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: $APP_SEED
services:
  main:
    image: codercom/code-server:4.90.3@sha256:f54483e9794f1bbd42bf55346ebeadb057a4f0dc9da1a50670e3a335ee295a35
    user: 1000:1000
    environment:
      PASSWORD: $APP_SEED
    port: 8080
    mounts:
      data:
        data: /home/coder
