citadel_version: 4
metadata:
  name: code-server
  version: 4.90.1
  category: Development
  tagline: Run VS Code on your Citadel
  developers:
    Coder: https://coder.com
  description: This app doesn't  have a description yet.
  permissions: []
  repo:
    Public: https://github.com/cdr/code-server
  support: https://github.com/cdr/code-server/discussions
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: $APP_SEED
services:
  main:
    image: codercom/code-server:4.90.1@sha256:5d85938ed45660b18934fa54de7274d0b5635c5e246d2b61bca523288005e6bd
    user: 1000:1000
    environment:
      PASSWORD: $APP_SEED
    port: 8080
    mounts:
      data:
        data: /home/coder
