citadel_version: 4
metadata:
  name: code-server
  version: 4.20.0
  category: Development
  tagline: Run VS Code on your Citadel
  developers:
    Coder: https://coder.com
  description: This app doesn't  have a description yet.
  permissions: []
  repo:
    Public: https://github.com/cdr/code-server
  support: https://github.com/cdr/code-server/discussions
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: $APP_SEED
services:
  main:
    image: codercom/code-server:4.20.0@sha256:945c1c6452a3ac798283a6f43fb0c815e4c0e9418bceec37eac6d6bd378b5e99
    user: 1000:1000
    environment:
      PASSWORD: $APP_SEED
    port: 8080
    mounts:
      data:
        data: /home/coder
