citadel_version: 4
metadata:
  name: Lightning Terminal
  version: 0.14.0-alpha.rc1
  category: Lightning Node Management
  tagline: A browser-based interface for managing channel liquidity
  developers:
    Lightning Labs: https://lightning.engineering
  description: |-
    With Lightning Terminal, you can
      - Visualize your channels and balances

      - Perform submarine swaps via the Lightning Loop service

      - Classify channels according to your node's operating mode

      - Run a single binary that integrates loopd, poold and faraday daemons all in one

      - Access a preview release of the Pool UI

      - Use Pool to earn sats by opening channels to those needing inbound liquidity
  permissions:
  - lnd
  repo:
    Public: https://github.com/lightninglabs/lightning-terminal
  support: https://github.com/lightninglabs/lightning-terminal/issues
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  - 4.jpg
  defaultPassword: $APP_SEED
services:
  web:
    image: lightninglabs/lightning-terminal:v0.14.0-alpha.rc1@sha256:5092fa54641a22db4ab0becf64b33383a0cc2906a71a201071dc087d20d55269
    user: 1000:1000
    command:
    - --insecure-httplisten=0.0.0.0:3000
    - --network="$BITCOIN_NETWORK"
    - --lnd-mode="remote"
    - --remote.lnd.rpcserver=$LND_IP:$LND_GRPC_PORT
    - --remote.lnd.macaroonpath="/lnd/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon"
    - --remote.lnd.tlscertpath="/lnd/tls.cert"
    - --uipassword="${APP_SEED}"
    environment:
      HOME: /data
    port: 3000
    mounts:
      data:
        data: /data
      lnd: /lnd
