name: Check app updates

on:
  workflow_dispatch:
  schedule: 
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Check for updates
        run: |
          cd ..
          git clone https://github.com/citadel-core/app-manager
          cd app-manager
          # TODO: Use prebuilts/Docker
          cargo run --features=cli,dev-tools -- update ../apps --token "${{ secrets.GITHUB_TOKEN }}"
          cd ..
          rm -rf app-manager
          cd apps
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -a -m "chore: Update apps" || true
          git push
